### ISSUE TITLE
Fix gh-pages deployment

### ISSUE THREAD

**Issue by adcaelum** [adcaelum/adcaelum.github.io#6]

**Comment by juliuscc** [comment]
You should try vercel. It is a one-click thing that just magically puts your website online, and syncs with your repo. It is created by the same company that creates Next, and is free for always for hobby projects of any size.

**Comment by juliuscc** [comment]
I was a stupid boi for ever showing you github actions when vercel exists

**Comment by adcaelum** [comment]
😱 OMG thank you I will look at it!! @juliuscc

**Comment by adcaelum** [comment]
WOW that was SO easy @juliuscc

**Comment by juliuscc** [comment]
Yup! Vercel is magic 🪄✨

bippity boppity boo

![✨](https://giphy.com/gifs/reaction-gif-fkG8iikX3nZRu)
